#!/usr/bin/env perl
use v5.20;
use DDP;
use Me::Schema;
use lib '.';

my $schema = Me::Schema->connect('dbi:SQLite:Me.db');

# retrieve the upload
my $upload = $schema->resultset('Upload')->find(1);


# get the absolute path
say $upload->file->absolute;

say $upload->ts;
say $upload->name;
# get the mime type (image/png)
p $upload->mime;

# get the file extension
p $upload->extension;

__END__
# get a read filehandle
$upload->file->openr;

# get a write filehandle
$upload->file->openw;

# get an append filehandle
$upload->file->opena;)))
